- name: update vault servers
  hosts: all
  become: yes

  tasks:
    - name: generate vault hcl files
      template:
        src: vault.j2
        dest: /etc/vault.d/vault.hcl
      notify:
        - stop vault

  handlers:
    - name: stop vault
      service: name=vault state=stopped

- name: start last server
  hosts: vault-6
  become: yes

  tasks:
    - name: start vault
      service: name=vault state=started

    - name: grant vagrant executable
      acl:
        path: /usr/local/bin/vault
        entity: vagrant
        etype: user
        permissions: x
        state: present

    - name: vault status
      shell: /usr/local/bin/vault operator init > token.txt
      environment:
        VAULT_ADDR: http://127.0.0.1:8200


- name: start all vault servers
  hosts: all
  become: yes

  tasks:
    - name: start vault
      service: name=vault state=started
